// sendTemplates.js
//Temp js for filling templates in the db
const mongoose = require('mongoose');
const Template = require("./models/TemplateModel");

const templates = [
        {
      id: 1,
      name: "Professional Business Card",
      category: "Business",
      thumbnail: "https://via.placeholder.com/320x200/e2e8f0/475569?text=Professional",
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 600,
          height: 350,
          fill: "#ffffff",
          opacity: 1,
          rotation: 0,
        },
        {
          id: 2,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 600,
          height: 100,
          fill: "#3b82f6",
          opacity: 1,
          rotation: 0,
        },
        {
          id: 3,
          type: "text",
          x: 50,
          y: 150,
          width: 300,
          height: 40,
          text: "John Doe",
          fontSize: 28,
          fontFamily: "Arial",
          color: "#333333",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
        {
          id: 4,
          type: "text",
          x: 50,
          y: 190,
          width: 300,
          height: 30,
          text: "Software Developer",
          fontSize: 18,
          fontFamily: "Arial",
          color: "#666666",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
        {
          id: 5,
          type: "text",
          x: 50,
          y: 230,
          width: 300,
          height: 20,
          text: "john@example.com | (123) 456-7890",
          fontSize: 14,
          fontFamily: "Arial",
          color: "#666666",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
      ],
    },
    {
      id: 2,
      name: "Creative Designer Card",
      category: "Design",
      thumbnail: "https://via.placeholder.com/320x200/dbeafe/1e40af?text=Creative",
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 600,
          height: 350,
          fill: "#f8fafc",
          opacity: 1,
          rotation: 0,
        },
        {
          id: 2,
          type: "circle",
          x: 450,
          y: 50,
          width: 100,
          height: 100,
          fill: "#ec4899",
          opacity: 0.8,
          rotation: 0,
        },
        {
          id: 3,
          type: "text",
          x: 50,
          y: 150,
          width: 300,
          height: 40,
          text: "Sarah Johnson",
          fontSize: 32,
          fontFamily: "Georgia",
          color: "#111827",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
        {
          id: 4,
          type: "text",
          x: 50,
          y: 200,
          width: 300,
          height: 30,
          text: "Graphic Designer",
          fontSize: 20,
          fontFamily: "Georgia",
          color: "#4f46e5",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
        {
          id: 5,
          type: "text",
          x: 50,
          y: 240,
          width: 300,
          height: 20,
          text: "sarah@design.com | (987) 654-3210",
          fontSize: 14,
          fontFamily: "Georgia",
          color: "#6b7280",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
      ],
    },
    {
      id: 3,
      name: "Minimalist Tech Card",
      category: "Tech",
      thumbnail: "https://via.placeholder.com/320x200/f0fdf4/166534?text=Minimalist",
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 600,
          height: 350,
          fill: "#18181b",
          opacity: 1,
          rotation: 0,
        },
        {
          id: 2,
          type: "rectangle",
          x: 50,
          y: 50,
          width: 100,
          height: 5,
          fill: "#22c55e",
          opacity: 1,
          rotation: 0,
        },
        {
          id: 3,
          type: "text",
          x: 50,
          y: 150,
          width: 300,
          height: 40,
          text: "ALEX CHEN",
          fontSize: 28,
          fontFamily: "Courier New",
          color: "#ffffff",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
        {
          id: 4,
          type: "text",
          x: 50,
          y: 190,
          width: 300,
          height: 30,
          text: "FULL-STACK DEVELOPER",
          fontSize: 16,
          fontFamily: "Courier New",
          color: "#22c55e",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
        {
          id: 5,
          type: "text",
          x: 50,
          y: 230,
          width: 300,
          height: 20,
          text: "alex@tech.io | github.com/alexchen",
          fontSize: 14,
          fontFamily: "Courier New",
          color: "#d1d5db",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
      ],
    },
    {
      id: 4,
      name: "Elegant Corporate Card",
      category: "Corporate",
      thumbnail: "https://via.placeholder.com/320x200/fef2f2/991b1b?text=Elegant",
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 600,
          height: 350,
          fill: "#f8fafc",
          opacity: 1,
          rotation: 0,
        },
        {
          id: 2,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 20,
          height: 350,
          fill: "#7f1d1d",
          opacity: 1,
          rotation: 0,
        },
        {
          id: 3,
          type: "text",
          x: 50,
          y: 150,
          width: 300,
          height: 40,
          text: "Michael Roberts",
          fontSize: 28,
          fontFamily: "Times New Roman",
          color: "#1e293b",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
        {
          id: 4,
          type: "text",
          x: 50,
          y: 190,
          width: 300,
          height: 30,
          text: "Chief Executive Officer",
          fontSize: 18,
          fontFamily: "Times New Roman",
          color: "#7f1d1d",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
        {
          id: 5,
          type: "text",
          x: 50,
          y: 230,
          width: 300,
          height: 20,
          text: "michael@company.com | (555) 123-4567",
          fontSize: 14,
          fontFamily: "Times New Roman",
          color: "#64748b",
          opacity: 1,
          rotation: 0,
          textAlign: "left",
        },
      ],
    },
];

const start = async () => {
  try {
    await mongoose.connect('mongodb+srv://aimanahzaz88:Aahzaz04@clusterone.cqpiufm.mongodb.net/Cardify?retryWrites=true&w=majority'); // adjust DB name if needed
    console.log("Connected to MongoDB");

    await Template.deleteMany(); // optional: clears old data
    await Template.insertMany(templates);
    console.log("Templates inserted");

    mongoose.disconnect();
  } catch (error) {
    console.error("Error seeding templates:", error);
  }
};

start();
